web:
    image: nginx:latest
    container_name: web
    ports:
        - "8888:80"
    volumes:
        - ./conf/site.conf:/etc/nginx/conf.d/default.conf
        - ./log/access.log:/var/log/access.log
    links:
        - php
php:
    image: php:7.2-apache
    container_name: php
    volumes:
        - ./code:/var/www/html